version: '3.8'
services:
  mysql:
    container_name: 'mvc-rdb'
    image: mysql:8.0
    ports:
      - "33306:3306"
    volumes:
      - ./mvc_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'cooper2025'
      MYSQL_DATABASE: cooper_db
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
